### ISSUE TITLE
Tooltip not showing the right amount of damage for styles

### ISSUE THREAD

**Issue by dkhlink** [OpenDAoC/OpenDAoC-Core#37]
For any styles, the tooltip will show "Low" as Damage, no matter the style.

![image](https://github.com/OpenDAoC/OpenDAoC-Core/assets/51218867/c36b1571-3ee4-4414-a2ae-0c3327669c6a)

Should be the case all for style but just tested on Thane.

**Comment by dkhlink** [comment]
Also tested on warrior "Hammer" only shows Damage = None, Damage = Very Low, Damage = Low for all styles.

**Comment by bm01** [comment]
A few things to point out, the server doesn't tell the client what text to display, but sends it the growth rate modified by a constant. This is then interpreted by the client.

The reason why a constant value is needed is because it's unlikely that the way DoL-based servers calculate damage matches the way official servers do or did. The formula was elaborated from in-game observations, but there are probably different ways to get to the same result. The trick is to figure out that constant. Assuming it's actually a constant.

There's also the question of patch accuracy. Tooltips were very inaccurate back in the days, and if we refer to the prima guide, Reaper (level 2 style) was shown doing medium damage and Nature's Shield (level 25 blocking style that actually did 0) shown doing low damage. This is just two examples, but it affects other lines too. Tooltips were simply very unreliable and misleading.

I don't think making it accurate for 1.65 is a good idea in this case, so I'll probably just tweak the constant until "it feels right". But since we're using 1.65 styles, that means the result may not match your source's.

With that made clear, here's the value ranges used by the currently used clients:
```
[..0]		none
[0,50]		low
[51,149]	medium
[150,190]	high
[191,499]	very high
[500..]		devastating
```
Changing the constant from 100 to 175 gives the following result:
```
Becomes...	| GR
low at		| 0.2914285714
medium at 	| 0.5714285714
high at		| 0.8571428571
very high at 	| 1.091428571
devastating at	| 2.857142857
```
Looks fine to me but I haven't checked all lines. I'll wait a bit before applying this change in case someone finds a better value.
